version: '3.7'
services:
  frontend:
    container_name: EOLO_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - '3000:3000'
